server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.36.44.148:3306/recruitment?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 83ec64005ba39e58


  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  freemarker:
    cache: true
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: yunhao.demo3.entity
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true